// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAi2OgMWRI6VW_9gGbpv61IoBD3bfw-aA',
    appId: '1:822566974798:web:e8cdea2a0b1c34e3201a1f',
    messagingSenderId: '822566974798',
    projectId: 'crud-firebase-78ff9',
    authDomain: 'crud-firebase-78ff9.firebaseapp.com',
    storageBucket: 'crud-firebase-78ff9.appspot.com',
    measurementId: 'G-5K6GF4LZ0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSRk4AhuwMmAzP7LIsqtbhxKJclh2lhg',
    appId: '1:822566974798:android:4a2e47ef9773db3d201a1f',
    messagingSenderId: '822566974798',
    projectId: 'crud-firebase-78ff9',
    storageBucket: 'crud-firebase-78ff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDboie-yNZ0ZH0ZGBnBbW9kvFgtvZ6Ixbk',
    appId: '1:822566974798:ios:745c448ae5cb19fb201a1f',
    messagingSenderId: '822566974798',
    projectId: 'crud-firebase-78ff9',
    storageBucket: 'crud-firebase-78ff9.appspot.com',
    iosBundleId: 'com.example.firebaseCrudApp',
  );
}
